"""Wire protocol for the vmoji telemetry link.

This module is deliberately free of any Qt dependency. Everything here is plain
Python, so the parser can be unit tested with pytest, fuzzed, and reused from a
headless script. The GUI layer is a consumer of this module, never the reverse.

The frame layout is defined once, in ``blink/telemetry_frame.h``. The reference
vectors in ``tests/test_protocol.py`` are generated by the C++ self-test, which
is what keeps the two implementations honest with each other.

    offset  size  field
    0       2     sync word 0xAA 0x55
    2       2     payload length, u16 little-endian
    4       1     message id
    5       1     sequence number
    6       N     payload
    6+N     2     CRC-16/CCITT-FALSE over offsets [2, 6+N)
"""

from __future__ import annotations

import struct
import time
from dataclasses import dataclass, field
from enum import IntEnum
from typing import Callable, Iterator

SYNC = b"\xaa\x55"
SYNC0 = 0xAA
SYNC1 = 0x55

HEADER_SIZE = 6
CRC_SIZE = 2
OVERHEAD = HEADER_SIZE + CRC_SIZE
MAX_PAYLOAD = 255
MAX_FRAME = MAX_PAYLOAD + OVERHEAD


class MsgId(IntEnum):
    STATUS = 0x01
    FRAMEBUFFER = 0x02
    LOG = 0x03
    ACK = 0x10


class StatusFlag(IntEnum):
    ACTIVITY = 0x01
    OVERRUN = 0x02
    PAUSED = 0x04
    TX_DROP = 0x08  # firmware discarded a frame; a link could not keep up


# ---------------------------------------------------------------------------
# CRC-16/CCITT-FALSE (poly 0x1021, init 0xFFFF, no reflection)
# ---------------------------------------------------------------------------


def _build_crc_table() -> tuple[int, ...]:
    table = []
    for index in range(256):
        crc = index << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
        table.append(crc)
    return tuple(table)


_CRC_TABLE = _build_crc_table()


def crc16(data: bytes, seed: int = 0xFFFF) -> int:
    crc = seed
    for byte in data:
        crc = ((crc << 8) ^ _CRC_TABLE[((crc >> 8) ^ byte) & 0xFF]) & 0xFFFF
    return crc


# ---------------------------------------------------------------------------
# Decoded messages
# ---------------------------------------------------------------------------

_STATUS_STRUCT = struct.Struct("<IIHHHHHhHHIHBB")
assert _STATUS_STRUCT.size == 32, "StatusPayload layout drifted from the firmware"


@dataclass(frozen=True)
class Status:
    """One reporting interval of firmware health and timing metrics."""

    host_time: float
    seq: int
    uptime_ms: int
    scan_count: int
    refresh_chz: int
    period_mean_us: int
    period_min_us: int
    period_max_us: int
    jitter_pp_us: int
    die_temp_c_x100: int
    cmd_ok: int
    cmd_err: int
    rx_bytes: int
    row_dwell_us: int
    glyph_id: int
    flags: int

    @property
    def refresh_hz(self) -> float:
        return self.refresh_chz / 100.0

    @property
    def die_temp_c(self) -> float:
        return self.die_temp_c_x100 / 100.0

    @property
    def uptime_s(self) -> float:
        return self.uptime_ms / 1000.0

    def has_flag(self, flag: StatusFlag) -> bool:
        return bool(self.flags & int(flag))

    @classmethod
    def unpack(cls, payload: bytes, host_time: float, seq: int) -> "Status":
        # unpack_from, not unpack: a longer payload means newer firmware has
        # appended fields this host does not know about. Decoding the prefix we
        # do understand keeps an older dashboard usable against a newer board,
        # which is the whole reason the length is on the wire.
        fields = _STATUS_STRUCT.unpack_from(payload, 0)
        return cls(host_time, seq, *fields)


@dataclass(frozen=True)
class FrameBuffer:
    """The 8x8 bitmap currently being scanned. Bit 7 of each row is column 0."""

    host_time: float
    seq: int
    rows: tuple[int, ...]

    def pixel(self, row: int, col: int) -> bool:
        return bool(self.rows[row] & (0x80 >> col))

    def as_grid(self) -> list[list[bool]]:
        return [[self.pixel(r, c) for c in range(8)] for r in range(8)]

    @classmethod
    def unpack(cls, payload: bytes, host_time: float, seq: int) -> "FrameBuffer":
        return cls(host_time, seq, tuple(payload[:8]))


@dataclass(frozen=True)
class TextMessage:
    """A Log or Ack message. Kept as one type since they differ only in intent."""

    host_time: float
    seq: int
    msg_id: MsgId
    text: str


@dataclass(frozen=True)
class UnknownMessage:
    """An id this build of the host does not recognise.

    Forward compatibility matters for a tool that outlives a firmware revision:
    an unknown message is surfaced and counted, never treated as a parse error.
    """

    host_time: float
    seq: int
    raw_id: int
    payload: bytes


Message = Status | FrameBuffer | TextMessage | UnknownMessage


# ---------------------------------------------------------------------------
# Parser statistics
# ---------------------------------------------------------------------------


@dataclass
class ParserStats:
    """Link health. A debug tool that cannot tell you the link is degrading is
    worse than no tool, because it invites you to trust the plot."""

    bytes_in: int = 0
    frames_ok: int = 0
    crc_errors: int = 0
    length_errors: int = 0
    unknown_ids: int = 0
    resync_bytes: int = 0
    seq_gaps: int = 0
    frames_dropped_estimate: int = 0

    @property
    def error_rate(self) -> float:
        total = self.frames_ok + self.crc_errors + self.length_errors
        return self.crc_errors / total if total else 0.0

    def as_rows(self) -> list[tuple[str, str]]:
        return [
            ("Bytes received", f"{self.bytes_in:,}"),
            ("Frames OK", f"{self.frames_ok:,}"),
            ("CRC errors", str(self.crc_errors)),
            ("Bad lengths", str(self.length_errors)),
            ("Unknown ids", str(self.unknown_ids)),
            ("Resync bytes", f"{self.resync_bytes:,}"),
            ("Sequence gaps", str(self.seq_gaps)),
            ("Frames lost (est.)", str(self.frames_dropped_estimate)),
        ]


# ---------------------------------------------------------------------------
# The parser
# ---------------------------------------------------------------------------


class FrameParser:
    """Incremental byte-stream parser.

    Serial delivers arbitrary chunks, not messages: a read can return half a
    frame, three frames, or a frame plus the boot banner. So the parser holds a
    buffer across calls and yields only whole, CRC-verified frames.

    Resynchronisation is the part that matters in practice. On a bad CRC or a
    bogus length the parser advances past the offending sync word and keeps
    hunting, rather than discarding the buffer or stalling. That is what lets you
    attach to a device that is already running, mid-frame, and start decoding
    within one message.
    """

    def __init__(self, clock: Callable[[], float] = time.monotonic) -> None:
        self._buffer = bytearray()
        self._clock = clock
        self._last_seq: int | None = None
        self.stats = ParserStats()

    def reset(self) -> None:
        self._buffer.clear()
        self._last_seq = None

    @property
    def pending_bytes(self) -> int:
        return len(self._buffer)

    def feed(self, chunk: bytes) -> list[Message]:
        """Absorb a chunk and return every complete message it completed."""
        if chunk:
            self._buffer.extend(chunk)
            self.stats.bytes_in += len(chunk)
        return list(self._drain())

    def _drain(self) -> Iterator[Message]:
        buf = self._buffer
        while True:
            start = buf.find(SYNC)
            if start < 0:
                # No sync word. Keep only the last byte, in case it is the first
                # half of a sync word split across two reads.
                if len(buf) > 1:
                    self.stats.resync_bytes += len(buf) - 1
                    del buf[:-1]
                return

            if start > 0:
                self.stats.resync_bytes += start
                del buf[:start]

            if len(buf) < HEADER_SIZE:
                return

            payload_size = buf[2] | (buf[3] << 8)
            if payload_size > MAX_PAYLOAD:
                self.stats.length_errors += 1
                del buf[:2]
                continue

            total = payload_size + OVERHEAD
            if len(buf) < total:
                return

            body = bytes(buf[2 : HEADER_SIZE + payload_size])
            expected = crc16(body)
            actual = buf[HEADER_SIZE + payload_size] | (buf[HEADER_SIZE + payload_size + 1] << 8)
            if expected != actual:
                self.stats.crc_errors += 1
                del buf[:2]
                continue

            raw_id = buf[4]
            seq = buf[5]
            payload = bytes(buf[HEADER_SIZE : HEADER_SIZE + payload_size])
            del buf[:total]

            self.stats.frames_ok += 1
            self._check_sequence(seq)
            yield self._decode(raw_id, seq, payload)

    def _check_sequence(self, seq: int) -> None:
        if self._last_seq is not None:
            expected = (self._last_seq + 1) & 0xFF
            if seq != expected:
                self.stats.seq_gaps += 1
                self.stats.frames_dropped_estimate += (seq - expected) & 0xFF
        self._last_seq = seq

    def _decode(self, raw_id: int, seq: int, payload: bytes) -> Message:
        now = self._clock()
        try:
            msg_id = MsgId(raw_id)
        except ValueError:
            self.stats.unknown_ids += 1
            return UnknownMessage(now, seq, raw_id, payload)

        if msg_id is MsgId.STATUS and len(payload) >= _STATUS_STRUCT.size:
            return Status.unpack(payload, now, seq)
        if msg_id is MsgId.FRAMEBUFFER and len(payload) >= 8:
            return FrameBuffer.unpack(payload, now, seq)
        if msg_id in (MsgId.LOG, MsgId.ACK):
            return TextMessage(now, seq, msg_id, payload.decode("ascii", errors="replace"))

        # Right shape of frame, wrong size of payload: a firmware/host version
        # mismatch. Surface it rather than unpacking garbage.
        self.stats.unknown_ids += 1
        return UnknownMessage(now, seq, raw_id, payload)


# ---------------------------------------------------------------------------
# Encoding (used by the simulator and the tests)
# ---------------------------------------------------------------------------


def encode_frame(msg_id: int, seq: int, payload: bytes = b"") -> bytes:
    if len(payload) > MAX_PAYLOAD:
        raise ValueError(f"payload of {len(payload)} bytes exceeds {MAX_PAYLOAD}")
    body = struct.pack("<HBB", len(payload), int(msg_id), seq & 0xFF) + payload
    return SYNC + body + struct.pack("<H", crc16(body))


def pack_status_payload(
    *,
    uptime_ms: int = 0,
    scan_count: int = 0,
    refresh_chz: int = 0,
    period_mean_us: int = 0,
    period_min_us: int = 0,
    period_max_us: int = 0,
    jitter_pp_us: int = 0,
    die_temp_c_x100: int = 0,
    cmd_ok: int = 0,
    cmd_err: int = 0,
    rx_bytes: int = 0,
    row_dwell_us: int = 0,
    glyph_id: int = 0,
    flags: int = 0,
) -> bytes:
    return _STATUS_STRUCT.pack(
        uptime_ms,
        scan_count,
        refresh_chz,
        period_mean_us,
        period_min_us,
        period_max_us,
        jitter_pp_us,
        die_temp_c_x100,
        cmd_ok,
        cmd_err,
        rx_bytes,
        row_dwell_us,
        glyph_id,
        flags,
    )


def encode_status(seq: int, **fields: int) -> bytes:
    return encode_frame(MsgId.STATUS, seq, pack_status_payload(**fields))


def encode_framebuffer(seq: int, rows: bytes) -> bytes:
    if len(rows) != 8:
        raise ValueError("framebuffer needs exactly 8 rows")
    return encode_frame(MsgId.FRAMEBUFFER, seq, bytes(rows))


# ---------------------------------------------------------------------------
# Host commands
#
# The uplink stays ASCII and line-oriented so the board can still be driven from
# a plain terminal during bring-up. Binary framing earns its keep on the
# high-rate downlink, not on six commands a minute typed by a human.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Command:
    line: str
    description: str

    def encode(self) -> bytes:
        return (self.line + "\n").encode("ascii")


def cmd_score(home: int, away: int) -> Command:
    return Command(f"S {home} {away}", f"set score {home}-{away}")


def cmd_glyph(glyph_id: int) -> Command:
    return Command(f"G {glyph_id}", f"select glyph {glyph_id}")


def cmd_dwell(microseconds: int) -> Command:
    return Command(f"D {microseconds}", f"set row dwell to {microseconds} us")


def cmd_heartbeat() -> Command:
    return Command("H", "heartbeat")


def cmd_blank() -> Command:
    return Command("B", "blank display")


def cmd_pause() -> Command:
    return Command("P", "toggle scan pause")


def cmd_reset_counters() -> Command:
    return Command("Z", "reset counters")


def cmd_query() -> Command:
    return Command("?", "query configuration")


def cmd_identity() -> Command:
    return Command("I", "report firmware version and board id")


IDENTITY_PREFIX = "ID "


def parse_identity(text: str) -> dict[str, str] | None:
    """Decode `ID vmoji <ver> sha=<sha> board=<serial>`, or None.

    The board serial is the point: it names one physical chip, which is how a
    viewer can tell a live board from the simulator at a glance.
    """
    if not text.startswith(IDENTITY_PREFIX):
        return None
    fields: dict[str, str] = {}
    parts = text[len(IDENTITY_PREFIX):].split()
    if parts and parts[0] == "vmoji":
        parts = parts[1:]
        if parts and "=" not in parts[0]:
            fields["version"] = parts[0]
            parts = parts[1:]
    for part in parts:
        key, sep, value = part.partition("=")
        if sep:
            fields[key] = value
    return fields or None


GLYPH_NAMES: tuple[str, ...] = (
    "blank",
    "heart",
    "letter P",
    "letter R",
    "checkerboard",
    "all on",
)
